[package]
name = "rustman"
version = "0.1.0"
authors = ["yukihirop <te108186@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
colored = "2.0.0"
crossbeam-channel = "0.5.0"
dotenv = "0.15.0"
nix = "0.19.0"
regex = "1.4.2"
signal-hook = "0.1.16"
structopt = "0.3.20"

[dev-dependencies]
anyhow = "1.0.34"
libc = "0.2.80"
tempfile = "3.1.0"
