version: "3"
services:
  export_upstart:
    build: .
    volumes:
      - ./tmp/upstart:/etc/init
      - ./fixtures:/home/app
    entrypoint: /bin/sh -c "initctl reload-configuration && while :; do sleep 10; done"
  export_systemd:
    build: .
    volumes:
      - ./tmp/systemd:/etc/systemd/system
      - ./fixtures:/home/app
    entrypoint: /bin/sh -c "initctl reload-configuration && while :; do sleep 10; done"
  export_supervisord:
    build: .
    volumes:
      - ./tmp/supervisord:/etc/supervisor/conf.d
      - ./fixtures:/home/app
    entrypoint: |-
        /bin/sh -c "mkdir -p /var/log/app && touch /var/log/app/{exit_0-1,exit_1-1,loop-1}.log && touch /var/log/app/{exit_0-1,exit_1-1,loop-1}.error.log && while :; do sleep 10; done"
